id: P002977
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN6876
  title: སློབ་ཕྲུག་ཡོན་ཏན་དང་ཁྱིམ་བདག་དོན་གྲུབ།
  author: ''
  volumes:
    281e967a376f40e99b4a78b2bf98497c:
      image_group_id: I3CN6878
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
