id: I2EE7B692
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:17:53+00:00'
last_modified: '2022-06-07T16:43:10.977765+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6876
  title: སློབ་ཕྲུག་ཡོན་ཏན་དང་ཁྱིམ་བདག་དོན་གྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    '8814':
      image_group_id: I3CN6878
      title: ''
      total_pages: 234
      order: 1
      base_file: 8814.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
